# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rgirondo <rgirondo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/11 12:59:34 by rgirondo          #+#    #+#              #
#    Updated: 2023/06/15 16:24:54 by rgirondo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.9'

services:
  
  nginx:

    depends_on:
      - wordpress
  
    build:

      context: ./

      dockerfile: ./requirements/nginx/Dockerfile

    container_name: nginx
    
    image: nginx_1

    ports: 
      - "443:443"

    volumes:
      - volumen_wordpress:/var/www/html

    networks:
      - network_1

    logging:
      driver: "none"
    
    restart: unless-stopped

  db:

    env_file:
      - ./.env

    build:

      context: ./

      dockerfile: ./requirements/mariadb/Dockerfile

    container_name: mariadb

    image: madriadb_1

    logging:
      driver: "none"

    volumes:
      - volumen_mariadb:/var/lib/mysql

    networks:
      - network_1

    restart: unless-stopped

  wordpress:

    depends_on:
      - db

    env_file:
      - ./.env

    build:

      context: ./

      dockerfile: ./requirements/wordpress-php/Dockerfile

    container_name: wordpress

    image: wordpress_1

    logging:
      driver: "none"

    volumes:
      - volumen_wordpress:/var/www/html

    networks:
      - network_1

    restart: unless-stopped

volumes:

  volumen_wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/rgirondo/data/wordpress
      o: bind
      type: none

  volumen_mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/rgirondo/data/mariadb
      o: bind
      type: none

networks:
  network_1: